batch_size: 32
buffer_size: 1000000
env: Taxi-v3
exploration_final_eps: 0.05
exploration_fraction: 0.1
exploration_initial_eps: 1.0
gamma: 0.99
gradient_steps: 1
learning_starts: 50000
lr: 0.0005
n_timesteps: 1000000
policy: MlpPolicy
policy_kwargs:
  net_arch:
  - 64
  - 64
seed: 0
target_update_interval: 10000
train_freq: 4
