batch_size: 64
buffer_size: 15000
env: highway-fast-v0
exploration_final_eps: 0.01
exploration_fraction: 0.75
exploration_initial_eps: 0.5
gamma: 0.8
gradient_steps: 1
learning_starts: 200
lr: 0.0005
n_timesteps: 150000
policy: MlpPolicy
policy_kwargs:
  net_arch:
  - 256
  - 256
seed: 0
target_update_interval: 50
train_freq: 1
